name: Go HTMX Websocket Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Setup Go Environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22.5

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod tidy

  build:
    name: Build Go Application
    runs-on: ubuntu-latest
    needs: setup  # Ensure this job runs after the setup job

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22.5

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        run: go build -o gol-htmx .

      - name: Run tests
        run: go test ./...

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: gol-htmx
          path: ./gol-htmx

  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: build  # Ensure this job runs after the build job

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: gol-htmx
          path: ./gol-htmx

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/go-sock-x:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/go-sock-x:latest

      - name: Deploy to VPS
        env:
              SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
              VPS_USER: ${{ secrets.VPS_USER }}
              VPS_HOST: ${{ secrets.VPS_HOST }}
        run: |
              # Create the SSH key file
              echo "${SSH_PRIVATE_KEY}" | tr -d '\r' > private_key
              chmod 600 private_key
        
              # Copy the Docker Compose file to the VPS
              scp -o StrictHostKeyChecking=no -i private_key docker-compose.yml ${VPS_USER}@${VPS_HOST}:/home/${VPS_USER}/docker-compose.yml
        
              # SSH into the VPS and run Docker Compose commands
              ssh -o StrictHostKeyChecking=no -i private_key ${VPS_USER}@${VPS_HOST} '
                docker-compose -f /home/${VPS_USER}/docker-compose.yml pull
                docker-compose -f /home/${VPS_USER}/docker-compose.yml up -d
              '
        
              # Clean up the SSH key file
              rm private_key
        

    # - name: Apply Database Migrations
    #   run: ./migrate -path ./migrations -database ${{ secrets.DATABASE_URL }} up

    # - name: Slack Notification
    #   uses: 8398a7/action-slack@v3
    #   with:
    #     status: ${{ job.status }}
    #     fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
    #   env:
    #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
