name: Go HTMX Websocket Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Go Application
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push Docker Image
        uses: docker/build-push-action@v4
        with: 
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/realtime-chat-htmx:latest

      - name: Notify Telegram
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            Build Stage Completed
            Job Status: ${{ job.status }}
            Repository: ${{ github.repository }}
            Branch: ${{ github.ref }}
            Commit: ${{ github.sha }}
            Author: ${{ github.actor }}
            
  deploy:
    needs: build
    name: Deploy Binary to VPS
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Deploy To VPS
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.VPS_USER }}
          host: ${{ secrets.VPS_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            whoami
            # Stop and remove old containers
            docker stop realtime-chat-htmx-container || true && docker rm realtime-chat-htmx-container || true
            # Pull and run the new container
            docker pull ${{ secrets.DOCKER_USERNAME }}/realtime-chat-htmx:latest
            docker -d -p 8080:8080 --name realtime-chat-htmx-container realtime-chat-htmx:latest

      - name: Notify Telegram
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            Build Stage Completed
            Job Status: ${{ job.status }}
            Repository: ${{ github.repository }}
            Branch: ${{ github.ref }}
            Commit: ${{ github.sha }}
            Author: ${{ github.actor }}