name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22.5

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests
      run: go test ./...
    
    - name: Login Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build Docker image
      run: docker build -t ${{ vars.DOCKER_USERNAME }}/go-sock-x:latest .

    - name: Push Docker image
      run: docker push ${{ vars.DOCKER_USERNAME }}/go-sock-x:latest

    # - name: Slack Notification
    #   uses: 8398a7/action-slack@v3
    #   with:
    #     status: ${{ job.status }}
    #     fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
    #   env:
    #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
